# =============================================================================
# @file    action.yml
# @brief   GitHub Action definition file for Waystation
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file named LICENSE in the repository
# @repo    https://github.com/caltechlibrary/waystation
# =============================================================================

name: 'Waystation'
description: "Archive a repository's GitHub Pages in the Wayback Machine"
author: 'Michael Hucka -- https://github.com/mhucka'
branding:
  icon: camera
  color: orange

inputs:
  dry_run:
    description: 'Print what would be done without actually doing it.'
    default: true
    required: false
  save_errors:
    # Corresponds to "saveErrors" in the Wayback Machine GitHub Action.
    description: 'Whether the Wayback Machine should save pages that return HTTP status 4xx-5xx.'
    default: false
    required: false
  save_outlinks:
    # Corresponds to "saveOutlinks" in the Wayback Machine GitHub Action.
    description: 'Whether the Wayback Machine should save links to external web pages.'
    default: true
    required: false
  save_screenshot:
    # Corresponds to "saveScreenshot" in the Wayback Machine GitHub Action.
    description: 'Whether the Wayback Machine should save a screenshot of the front page.'
    default: true
    required: false
  debug:
    description: 'Print context and variables in the GitHub Actions log.'
    default: false
    required: false
  GITHUB_TOKEN:
    description: 'GitHub token (automatically created by GitHub).'
    default: ${{ github.token }}
    required: false

runs:
  using: composite
  steps:
    - name: Get GitHub Pages URL.
      # This stores the URL in env.pages_url. The value will be "null" if
      # no pages URL is returned for any reason.
      id: s1
      shell: bash
      run: |
        echo pages_url=$(curl -s -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${{ inputs.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pages | jq '.html_url' | tr -d '"') >> $GITHUB_ENV

    - name: Dump GitHub Actions context and variables if debugging is on.
      id: s2
      if: inputs.debug == true || inputs.debug == 'true'
      env:
        # Setting this variable and then printing it below is not strictly
        # necessary; you could put the expression directly into the echo
        # command below. But when I do that, I get a doubling of the output.
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      shell: bash
      run: |
        echo "dry_run = ${{ inputs.dry_run }}"
        echo "pages_url = ${{ env.pages_url }}"
        echo "save_errors = ${{ inputs.save_errors }}"
        echo "save_outlinks = ${{ inputs.save_outlinks }}"
        echo "save_screenshots = ${{ inputs.save_screenshots }}"
        echo "debug = ${{ inputs.debug }}"
        echo "====================="
        echo "$GITHUB_CONTEXT"

    - name: Quit if GitHub Pages URL is null.
      id: s3
      if: startsWith(env.pages_url, 'null') == true
      uses: actions/github-script@v6.3.3
      with:
        script: |
          core.setFailed("Could not retrieve the GitHub Pages URL for repository ${{ github.repository }}.")

    - name: Proceed if this is not a dry run.
      id: s4
      if: startsWith(env.pages_url, 'null') != true && inputs.dry_run != true && inputs.dry_run != 'true'
      uses: JamieMagee/wayback@v1.3.19
      with:
        url: ${{ env.pages_url }}
        saveErrors: ${{ inputs.save_errors }}
        saveOutlinks: ${{ inputs.save_outlinks }}
        saveScreenshot: ${{ inputs.save_screenshot }}

    - name: Summarize the results of the run.
      id: s5
      shell: bash
      env:
        wm_url: https://web.archive.org/web/${{ env.pages_url }}
      run: |
        echo \#\# Results of sending the GitHub Pages to the Wayback Machine >> $GITHUB_STEP_SUMMARY
        echo Dry run: ${{ inputs.dry_run }}                                  >> $GITHUB_STEP_SUMMARY
        echo GitHub repository for this action: \`${{ github.repository }}\` >> $GITHUB_STEP_SUMMARY
        echo GitHub Pages URL for the repository: ${{ env.pages_url }}       >> $GITHUB_STEP_SUMMARY
        echo **URL in the Wayback Machine**: ${{ env.wm_url }}               >> $GITHUB_STEP_SUMMARY
        echo Date and time of this run: $(date "+%F %T (%Z)")                >> $GITHUB_STEP_SUMMARY
        echo ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓  >> $GITHUB_STEP_SUMMARY
        echo ┃ Note: sometimes the Wayback Machine takes extra long to    ┃  >> $GITHUB_STEP_SUMMARY
        echo ┃ start archiving a site. If this run of Waystation produced ┃  >> $GITHUB_STEP_SUMMARY
        echo ┃ an empty URL in the Wayback Machine above, wait an hour    ┃  >> $GITHUB_STEP_SUMMARY
        echo ┃ and then try to look up your GitHub Pages URL again by     ┃  >> $GITHUB_STEP_SUMMARY
        echo ┃ using the link above.                                      ┃  >> $GITHUB_STEP_SUMMARY
        echo ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛  >> $GITHUB_STEP_SUMMARY
