# GitHub Actions workflow to test Jamie Magee's GH action "Wayback".
#
# Copyright 2022-2024 California Institute of Technology.
# License: Modified BSD 3-clause – see file "LICENSE" in the project website.
# Website: https://github.com/caltechlibrary/waystation

name: Test Wayback
on:
  push:
    branches:
      - main
jobs:
  Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Run JamieMagee/wayback
      uses: JamieMagee/wayback@v1.3.28
      id: wayback
      with:
        url: https://caltechlibrary.github.io/waystation

    - name: Print results
      shell: bash
      run: |
        echo Wayback URL: ${{ steps.wayback.outputs.wayback_url }} >> $GITHUB_STEP_SUMMARY
