# GitHub Actions workflow to test Waystation.
#
# Copyright 2022-2024 California Institute of Technology.
# License: Modified BSD 3-clause – see file "LICENSE" in the project website.
# Website: https://github.com/caltechlibrary/waystation

name: "Test Waystation"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  Workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: caltechlibrary/waystation@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        debug: true
