# ╭─────────────────── Notice ── Notice ── Notice ───────────────────╮
# │ This is a custom Baler workflow file. It is different from the   │
# │ sample workflow suggested for users because it is designed to    │
# │ allow testing Baler. DO NOT COPY THIS FILE; instead, use the     │
# │ sample workflow file named "sample-workflow.yml" from the Baler  │
# │ source repository at https://github.com/caltechlibrary/baler/.   │
# ╰─────────────────── Notice ── Notice ── Notice ───────────────────╯

name: Test Waystation
run-name: Send GitHub Pages to the Wayback Machine

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without actually sending URLs"
        type: boolean
        default: true
      debug:
        default: true
        type: boolean
      save_errors:
        default: true
        type: boolean
      save_outlinks:
        default: true
        type: boolean
      save_screenshots:
        default: true
        type: boolean

jobs:
  Workflow:
    name: Run Waystation
    runs-on: ubuntu-latest
    steps:
      - uses: caltechlibrary/waystation@develop
        with:
          debug: ${{github.event.inputs.debug || true}}
          dry_run: ${{github.event.inputs.dry_run || true}}
          save_errors: ${{github.event.inputs.save_errors || false}}
          save_outlinks: ${{github.event.inputs.save_outlinks || false}}
          save_screenshot: ${{github.event.inputs.save_screenshot || false}}
