# ╭─────────────────── Notice ── Notice ── Notice ───────────────────╮
# │ This is a custom Waystation workflow file. It is different from  │
# │ the sample workflow suggested for users. DO NOT COPY THIS FILE;  │
# │ instead, use the sample workflow file "sample-workflow.yml" from │
# │ the repository at https://github.com/caltechlibrary/waystation/. │
# ╰─────────────────── Notice ── Notice ── Notice ───────────────────╯

name: Archive GitHub Pages
run-name: Send GitHub Pages to the Wayback Machine

on:
  release:
    types: [published]

jobs:
  run-waystation:
    name: Run Waystation
    runs-on: ubuntu-latest
    steps:
      - uses: caltechlibrary/waystation@main
        with:
          debug: true
